# Generated by Django 3.2.4 on 2023-02-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phpsupport', '0004_user_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='subscription',
            field=models.BooleanField(default=False),
        ),
    ]
