# Generated by Django 3.2.4 on 2023-02-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phpsupport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(verbose_name='Дата выполнения заказа'),
        ),
    ]
