# Generated by Django 3.2.4 on 2023-02-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phpsupport', '0002_auto_20230217_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='description_order',
            field=models.TextField(blank=True, null=True, verbose_name='Описание заказа'),
        ),
    ]
