# Generated by Django 3.2.4 on 2023-02-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phpsupport', '0003_alter_order_description_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.BooleanField(default=False),
        ),
    ]
